

CREATE TABLE `test` (
	`id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`value1` VARCHAR(255) NOT NULL DEFAULT '',
	`value2` TINYINT
) ENGINE=INNODB;

CREATE TABLE `testtest` (
	`id` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	`value1` VARCHAR(255) NOT NULL DEFAULT '',
	`value2` TINYINT
) ENGINE=INNODB;